### ISSUE TITLE
跨年提醒计算小BUG

### ISSUE THREAD

**Issue by HoHoYee** [2892211452/birthdayBot#3]
如现在是2021-12-29
农历生日得日期刚好是2022-01-01在调试过程中就发现只有当天能提醒得到了
![202112290944](https://user-images.githubusercontent.com/16457118/147620819-864ee466-cf4a-4cbd-b23b-3d74fecece72.png)
需要增加当前日期比提醒日期要大时候，年份+1即可避免

另外感谢作者开源，代码很好用，提醒很及时

**Comment by 2892211452** [comment]
感谢反馈已经做出调整
