### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by hexWars** [2892211452/birthdayBot#4]
可否增加对公历的支持,感觉过农历生日的很少

**Comment by 2892211452** [comment]
也可以，不过农历生日的感觉基本都可以通过手机日历设置，提醒更加精准，我就没做这套

**Comment by hexWars** [comment]
我发现了,有人做了公历的版本,貌似也是参考你的做的,你可以看一下[BirthdayReminder](https://github.com/Extrader-home/BirthdayReminder)

**Comment by 2892211452** [comment]
确实是，稍微改了一下交互逻辑，等我过一段时间有空了再看要不要升级一下吧。可以做成同时支持两种历法的

**Comment by 2892211452** [comment]
done

**Comment by Gungnir762** [comment]
> 可否增加对公历的支持,感觉过农历生日的很少

我基于此项目做了修改，可以支持公历。这是[我的项目 ](https://github.com/Gungnir762/birthdayReminder)，请指正。
