### ISSUE TITLE
关于安全问题的建议

### ISSUE THREAD

**Issue by Gungnir762** [2892211452/birthdayBot#6]
老哥你在config.yaml中暴露了两个QQ号和其中一个QQ号的授权码，这使得其他人可以很容易的使用你的QQ邮箱进行一些相关的灰色产业操作，今天我进行测试的时候发现你的发送邮箱已经被封了
![image](https://user-images.githubusercontent.com/83220033/209820845-0b0cd5fc-8a41-4d70-9f41-f8ca27cadae2.png)
所以我基于你的项目优化了一下配置参数的逻辑，并且使用对称加密对上传的信息文件进行处理，进一步避免暴露隐私。
这是[我的项目 ](https://github.com/Gungnir762/birthdayReminder)，请指正。

**Comment by 2892211452** [comment]
好的，多谢，我给你创建了一个pull request。咱俩一起完善一下吧

**Comment by Gungnir762** [comment]
> @Gungnir762 好的，多谢，我给你创建了一个pull request。咱俩一起完善一下吧

我觉得……可能我们两的代码merge起来有点困难，因为我的代码基本上是另起炉灶写的，借用的部分只有你关于日期判断的那部分代码 。

**Comment by 2892211452** [comment]
> > @Gungnir762 好的，多谢，我给你创建了一个pull request。咱俩一起完善一下吧
> 
> 我觉得……可能我们两的代码merge起来有点困难，因为我的代码基本上是另起炉灶写的，借用的部分只有你关于日期判断的那部分代码 。
哦哦，那好吧，当初我写这个项目的时候也没想太多，安全性方面确实欠考虑。有时间我完善一下，谢谢指正和思路。

**Comment by Gungnir762** [comment]
> 

不用谢，共同进步 =）
